### PR TITLE
using static files with express

### PR DESCRIPTION
**Pull request by frezdev**
Using `expres.static()` to load static files from the server and replacing the previous HTML template

### CODE REVIEW

**Comment by alejandroch1202** [comment]
@carlosandf That's the correct way to do it! That requiriment was pending but now it's solved. Great contribution.

**Comment by alejandroch1202** [comment]
It runs good in local but **it looks like Vercel does not render it correctly**. Here is the preview:
- https://express-api-git-fork-carlosandf-main-alejandroch1202.vercel.app/

What do you think it would be? :thinking:

**Comment by frezdev** [comment]
Fixing the error when deploying in vercel

- [https://express-api-carlosandf.vercel.app/](url)

**Review by alejandroch1202 — APPROVED** [review]
Great! Now it's working great with Vercel:
- https://express-nvj95fnba-alejandroch1202.vercel.app/

**Comment by alejandroch1202** [comment]
Sucessfully merged and now working in production. Thank you @carlosandf

**Pull request merged**
